G4E-6248 application manager rebranding
Glue42/toolbar pull request #40
Opened 2023-08-03 07:09 UTC by galin-iliev

2023-08-04 07:44 UTC, arjunah requested changes

2023-08-04 07:44 UTC, arjunah commented on README.md
> +# io.Connect Application Manager
Let's keep the Floating Toolbar name - io.Connect Floating Toolbar

2023-08-04 07:44 UTC, arjunah commented on app-config.json
> +  "name": "connect-application-manager",
io-connect-toolbar

2023-08-04 07:44 UTC, arjunah commented on app-config.json
> +      "appId": "connect-desktop-application-manager"
io-connect-toolbar

2023-08-04 07:44 UTC, arjunah commented on index.html
> +    <title>io.Connect Application Manager</title>
io.Connect Floating Toolbar

2023-08-08 07:25 UTC, galin-iliev commented
@arjunah all requested changes were implemented.

2023-08-08 09:36 UTC, arjunah approved these changes

2023-11-05 18:39 UTC, merged